name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          🎉 Thank you for submitting your first issue to **VentoyDocker**!  
          Your feedback helps us improve.  
          If you find this project useful, please consider giving it a ⭐️ to show your support!
        pr-message: |
          🙏🏻 Thank you for contributing your first pull request to **VentoyDocker**!  
          We appreciate your time and effort to make this project better.  
          If you haven’t already, consider starring ⭐️ the repository to stay connected.
